/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: c18b1ebc2252b2338088e136b2baa35d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SessionDurableObject" | "SyncedStateServer";
	}
	interface IntegrationEnv {
		FEATURE_FLAGS: KVNamespace;
		SESSION_SECRET_KEY: string;
		SESSION_DO: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		SYNCED_STATE_DO: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
	}
	interface StagingEnv {
		FEATURE_FLAGS: KVNamespace;
		SESSION_SECRET_KEY: string;
		SESSION_DO: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		SYNCED_STATE_DO: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
	}
	interface ProductionEnv {
		FEATURE_FLAGS: KVNamespace;
		SESSION_SECRET_KEY: string;
		SESSION_DO: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		SYNCED_STATE_DO: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
	}
	interface Env {
		FEATURE_FLAGS: KVNamespace;
		SESSION_SECRET_KEY: string;
		SESSION_DO: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		SYNCED_STATE_DO: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
		ASSETS?: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SESSION_SECRET_KEY">> {}
}
