/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: ccdf6a5107a222e905be67c10adc85c5)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SessionDurableObject" | "SyncedStateServer";
	}
	interface IntegrationEnv {
		GOLDEN_KEYS_MATRIX_ENV: string;
		SESSION_DO: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		SYNCED_STATE_DO: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
	}
	interface StagingEnv {
		GOLDEN_KEYS_MATRIX_ENV: string;
		SESSION_DO: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		SYNCED_STATE_DO: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
	}
	interface ProductionEnv {
		GOLDEN_KEYS_MATRIX_ENV: string;
		SESSION_DO: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		SYNCED_STATE_DO: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
	}
	interface Env {
		GOLDEN_KEYS_MATRIX_ENV: string;
		SESSION_DO: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
		SYNCED_STATE_DO: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
		ASSETS?: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOLDEN_KEYS_MATRIX_ENV">> {}
}
