/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: fc37ad824856d6a8486e199bc56d094b)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "SessionDurableObject" | "SyncedStateServer";
	}
	interface IntegrationEnv {}
	interface StagingEnv {}
	interface ProductionEnv {}
	interface Env {
		ASSETS?: Fetcher;
		SESSION_DO?: DurableObjectNamespace<import("./src/worker").SessionDurableObject>;
SYNCED_STATE_DO?: DurableObjectNamespace<import("./src/worker").SyncedStateServer>;
	}
}
interface Env extends Cloudflare.Env {}
